### ISSUE TITLE
Display differs from Svelte REPL console

### ISSUE THREAD

**Issue by techniq** [tanhauhau/svelte-json-tree#25]
When I try to display the output of a [d3-hierarchy](https://github.com/d3/d3-hierarchy) structure using `svelte-json-tree`, I only see `Iterable` in the display (1), but using `console.log()`, I see the desired output (2).

![image](https://github.com/tanhauhau/svelte-json-tree/assets/177476/1bb5184b-1751-4da4-b4e9-66dbe42d4830)

When I looked at the Svelte REPL [ConsoleLine.svelte](https://github.com/sveltejs/sites/blob/master/packages/repl/src/lib/Output/console/ConsoleLine.svelte), I didn't see any special handling, so I'm a little perplex why the output diffs (and how to accomplish the same outside of the REPL).

Here is an example [REPL](https://svelte.dev/repl/8ad63e35398540e6bca3e78689d483c4?version=4.2.1).

Thanks for any guidance!

**Comment by tanhauhau** [comment]
the d3.hierarchy is an iterable, that's why it is render as an iterable. the reason why it looks different in Svelte REPL, is because the data got serialised and deserialised through [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) (the repl output code is run inside and iframe, but the console is on the main window, so the console data is sent from the iframe out to the main window via `window.postMessage`)

**Comment by tanhauhau** [comment]
i've published [`v2.2.0`](https://github.com/tanhauhau/svelte-json-tree/blob/master/CHANGELOG.md#220) that allows you to treat iterable as normal object

**Comment by techniq** [comment]
@tanhauhau Perfect!  Thanks for the explanation and quick turnaround.

It allowed me to add a much nicer "View data" experience on all the hierarchy [LayerChart](https://www.layerchart.com/docs/examples/Pack) examples

Before | After
--- | ---
![image](https://github.com/tanhauhau/svelte-json-tree/assets/177476/1e5188a9-3352-4abd-afce-1e7abba40ae2) | ![image](https://github.com/tanhauhau/svelte-json-tree/assets/177476/48c7834b-c4c2-4ad1-af30-1fad8b80b98e)
